# Generated by Django 4.1.10 on 2023-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadbandAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(default='', max_length=50)),
                ('customerName', models.CharField(default='', max_length=50)),
                ('broadbandplan', models.CharField(default='', max_length=50)),
                ('mobileNo', models.CharField(default='', max_length=50)),
                ('subDate', models.CharField(default='', max_length=50)),
                ('NxtSubDate', models.CharField(default='', max_length=50)),
                ('amount', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=50)),
                ('ntwid', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
